[project]
name = "kiitos-tracker"
version = "0.1.0"
authors = [
    { name = "Andrea Sipos", email = "" },
    { name = "Peter Mitrano", email = "" },
]
description = "Add your description here"
requires-python = ">=3.12"
dependencies = []
